### ISSUE TITLE
Selecting or drag n drop doesn't work

### ISSUE THREAD

**Issue by TomerGamerTV** [Der-Floh/Cursor-Installer-Creator#1]
I try to drag file .cur files / select them and nothing changes

**Comment by Der-Floh** [comment]
Can you send me the cursor files you tried? so I can check whether they are the problem?

**Comment by TomerGamerTV** [comment]
> Can you send me the cursor files you tried? so I can check whether they are the problem?


[Hatsune Miku Cursors.zip](https://github.com/user-attachments/files/17014215/Hatsune.Miku.Cursors.zip)

**Comment by Der-Floh** [comment]
ok seems to have something to do with the location from where the cursor was selected from. Have to take a deeper look at that. But im gonna let you know when the bug is fixed

**Comment by Der-Floh** [comment]
Problem was with the encoding of the file path. It didn't work correctly cause of the space in the Path.
But that is now fixed in the [Latest Release](https://github.com/Der-Floh/Cursor-Installer-Creator/releases/latest)
